/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerReportAnggota;
import controller.ControllerReportHasil;
import controller.ControllerReportKriteria;
import controller.ControllerReportSubKriteria;
import controller.ControllerStartAnalisis;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ndull
 */
public class ViewMain extends javax.swing.JFrame {

    ControllerReportHasil hsl;
    ControllerReportKriteria ktr;
    ControllerReportAnggota agt;
    ControllerReportSubKriteria sub;
    /**
     * Creates new form ViewMain
     */
    public ViewMain() {
        initComponents();
         setLocationRelativeTo(null);
         hsl = new ControllerReportHasil(this);
         ktr = new ControllerReportKriteria(this);
         agt = new ControllerReportAnggota(this);
         sub = new ControllerReportSubKriteria(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuSiswa = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuKriteria = new javax.swing.JMenuItem();
        menuSubkriteria = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuBbtsiswa = new javax.swing.JMenuItem();
        menuBbtkriteria = new javax.swing.JMenuItem();
        menuBbtsubkriteria = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuexit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuAHP = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menuPerhitungan = new javax.swing.JMenuItem();
        menuHasilAHP = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenu4 = new javax.swing.JMenu();
        menuLapSiswa = new javax.swing.JMenuItem();
        menuLapKriteria = new javax.swing.JMenuItem();
        menuLapSubkriteria = new javax.swing.JMenuItem();
        menuLapPBeas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(238, 27, 44));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(java.awt.Color.white);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/report/logo.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Sistem Pendukung Keputusan");

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Penerima Bansos Pada Warga RW 001");

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Dengan Metode AHP");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel8)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        jMenu1.setText("Master Data");

        menuSiswa.setText("Data Warga");
        menuSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSiswaActionPerformed(evt);
            }
        });
        jMenu1.add(menuSiswa);
        jMenu1.add(jSeparator1);

        menuKriteria.setText("Data Kriteria");
        menuKriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKriteriaActionPerformed(evt);
            }
        });
        jMenu1.add(menuKriteria);

        menuSubkriteria.setText("Data Sub Kriteria");
        menuSubkriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSubkriteriaActionPerformed(evt);
            }
        });
        jMenu1.add(menuSubkriteria);

        jMenu3.setText("Pembobotan");

        menuBbtsiswa.setText("Bobot Warga");
        menuBbtsiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBbtsiswaActionPerformed(evt);
            }
        });
        jMenu3.add(menuBbtsiswa);

        menuBbtkriteria.setText("Bobot Kriteria");
        menuBbtkriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBbtkriteriaActionPerformed(evt);
            }
        });
        jMenu3.add(menuBbtkriteria);

        menuBbtsubkriteria.setText("Bobot Sub Kriteria");
        menuBbtsubkriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBbtsubkriteriaActionPerformed(evt);
            }
        });
        jMenu3.add(menuBbtsubkriteria);

        jMenu1.add(jMenu3);
        jMenu1.add(jSeparator2);

        menuexit.setText("Exit");
        menuexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuexitActionPerformed(evt);
            }
        });
        jMenu1.add(menuexit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Metode AHP");

        menuAHP.setText("Proses Perhitungan AHP");
        menuAHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAHPActionPerformed(evt);
            }
        });
        jMenu2.add(menuAHP);
        jMenu2.add(jSeparator3);

        menuPerhitungan.setText("Hasil Perhitungan Bobot");
        menuPerhitungan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPerhitunganActionPerformed(evt);
            }
        });
        jMenu2.add(menuPerhitungan);

        menuHasilAHP.setText("Hasil AHP Penerima Bansos");
        menuHasilAHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHasilAHPActionPerformed(evt);
            }
        });
        jMenu2.add(menuHasilAHP);
        jMenu2.add(jSeparator4);

        jMenu4.setText("Laporan");

        menuLapSiswa.setText("Laporan Warga");
        menuLapSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLapSiswaActionPerformed(evt);
            }
        });
        jMenu4.add(menuLapSiswa);

        menuLapKriteria.setText("Laporan Kriteria");
        menuLapKriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLapKriteriaActionPerformed(evt);
            }
        });
        jMenu4.add(menuLapKriteria);

        menuLapSubkriteria.setText("Laporan Sub Kriteria");
        menuLapSubkriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLapSubkriteriaActionPerformed(evt);
            }
        });
        jMenu4.add(menuLapSubkriteria);

        menuLapPBeas.setText("Laporan Penerima Bansos");
        menuLapPBeas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLapPBeasActionPerformed(evt);
            }
        });
        jMenu4.add(menuLapPBeas);

        jMenu2.add(jMenu4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSiswaActionPerformed
        // TODO add your handling code here:
        new ViewSupplier().setVisible(true);
    }//GEN-LAST:event_menuSiswaActionPerformed

    private void menuKriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKriteriaActionPerformed
        // TODO add your handling code here:
        new ViewKriteria().setVisible(true);
    }//GEN-LAST:event_menuKriteriaActionPerformed

    private void menuSubkriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSubkriteriaActionPerformed
        // TODO add your handling code here:
        new ViewSubKriteria().setVisible(true);
    }//GEN-LAST:event_menuSubkriteriaActionPerformed

    private void menuPerhitunganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPerhitunganActionPerformed
        // TODO add your handling code here:
        new ViewNilaiBobot().setVisible(true);
    }//GEN-LAST:event_menuPerhitunganActionPerformed

    private void menuHasilAHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHasilAHPActionPerformed
        // TODO add your handling code here:
        new ViewHasil().setVisible(true);
    }//GEN-LAST:event_menuHasilAHPActionPerformed

    private void menuLapSubkriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLapSubkriteriaActionPerformed
        // TODO add your handling code here:
        try {
            sub.ShowReport();
        } catch (SQLException ex) {
            Logger.getLogger(ViewHasil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuLapSubkriteriaActionPerformed

    private void menuBbtsiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBbtsiswaActionPerformed
        // TODO add your handling code here:
        new ViewSelectSupplier().setVisible(true);
    }//GEN-LAST:event_menuBbtsiswaActionPerformed

    private void menuBbtkriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBbtkriteriaActionPerformed
        // TODO add your handling code here:
        new ViewBobotKriteria().setVisible(true);
    }//GEN-LAST:event_menuBbtkriteriaActionPerformed

    private void menuBbtsubkriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBbtsubkriteriaActionPerformed
        // TODO add your handling code here:
        new ViewBobotSubKriteria().setVisible(true);
    }//GEN-LAST:event_menuBbtsubkriteriaActionPerformed

    private void menuAHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAHPActionPerformed
        // TODO add your handling code here:
        ControllerStartAnalisis controllerStartAnalisis = new ControllerStartAnalisis(this);
    }//GEN-LAST:event_menuAHPActionPerformed

    private void menuLapSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLapSiswaActionPerformed
        // TODO add your handling code here:
         try {
            agt.ShowReport();
        } catch (SQLException ex) {
            Logger.getLogger(ViewHasil.class.getName()).log(Level.SEVERE, null, ex);
        }
              
    }//GEN-LAST:event_menuLapSiswaActionPerformed

    private void menuLapKriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLapKriteriaActionPerformed
        // TODO add your handling code here:
        try {
            ktr.ShowReport();
        } catch (SQLException ex) {
            Logger.getLogger(ViewHasil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuLapKriteriaActionPerformed

    private void menuLapPBeasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLapPBeasActionPerformed
        // TODO add your handling code here:
        try {
            hsl.ShowReport();
        } catch (SQLException ex) {
            Logger.getLogger(ViewHasil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuLapPBeasActionPerformed

    private void menuexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuexitActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new ViewLogin().setVisible(true);
    }//GEN-LAST:event_menuexitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenuItem menuAHP;
    private javax.swing.JMenuItem menuBbtkriteria;
    private javax.swing.JMenuItem menuBbtsiswa;
    private javax.swing.JMenuItem menuBbtsubkriteria;
    private javax.swing.JMenuItem menuHasilAHP;
    private javax.swing.JMenuItem menuKriteria;
    private javax.swing.JMenuItem menuLapKriteria;
    private javax.swing.JMenuItem menuLapPBeas;
    private javax.swing.JMenuItem menuLapSiswa;
    private javax.swing.JMenuItem menuLapSubkriteria;
    private javax.swing.JMenuItem menuPerhitungan;
    private javax.swing.JMenuItem menuSiswa;
    private javax.swing.JMenuItem menuSubkriteria;
    private javax.swing.JMenuItem menuexit;
    // End of variables declaration//GEN-END:variables
}
